### ISSUE TITLE
Unable to build with VS 2019 (16.3.8)

### ISSUE THREAD

**Issue by markus-albis** [glennawatson/ReactiveGit#121]
4>Done building project "ReactiveGit.Gui.WPF.csproj" -- FAILED.
4>Done building project "ReactiveGit.Gui.WPF.csproj" -- FAILED.
========== Build: 2 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

First of many errors:

Argument 1: cannot convert from 'Splat.IMutableDependencyResolver' to 'Splat.IDependencyResolver'	ReactiveGit.Gui.Core (netstandard2.0)

**Comment by MueckeMa** [comment]
Same here.
What a pity I would like to learn a lot from this example.

**Comment by sergeylutski** [comment]
I know that I'm a little bit late with an answer, but maybe it will be useful for someone who enters  this thread as I just did: you can build and run the project successfully if checkout not latest master, but last "human" commit from Glenn Watson (now it's 7735b0e9d318d448cda7446f94b3340906fa8b27 from 4 Dec 2018 22:43).

I suppose latest master is not buildable because of updates of Nuget packages that were merged automatically without thorough testing.

**Comment by glennawatson** [comment]
I have a version offline I'll push in the next day or so that updates everything.

**Comment by sergeylutski** [comment]
Wow! Thanks a lot @glennawatson.
